adminset/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from adminset.views import index
from cmdb import asset

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^cmdb/', include('cmdb.urls')),
    url(r'^navi/', include('navi.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('setup.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^config/', include('config.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^appconf/', include('appconf.urls')),
    url(r'^delivery/', include('delivery.urls')),
    url(r'^mfile/', include('mfile.urls')),
    url(r'^elfinder/',include('elfinder.urls')),
    url(r'^branches/',include('branches.urls')),
    url(r'^webssh/(?P<ids>\d+)/$', asset.webssh, name='webssh'),

]

branches/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from branches import region, branch, resource

urlpatterns = [
    url(r'^$', region.region_list, name='branches'),
    url(r'^regionadd/$', region.region_add, name='region_add'),
    url(r'^region/$', region.region_list, name='region_list'),
    url(r'^regionbranchinfo/(?P<region_id>\d+)/$', region.branch_detail, name='branch_detail'),
    url(r'^regionedit/(?P<region_id>\d+)/$', region.region_edit, name='region_edit'),
    url(r'^regiondel/$', region.region_del, name='region_del'),
    url(r'^branchadd/$', branch.branch_add, name='branch_add'),
    url(r'^branch/$', branch.branch_list, name='branch_list'),
    url(r'^branchedit/(?P<branch_id>\d+)/$', branch.branch_edit, name='branch_edit'),
    url(r'^branchdel/$', branch.branch_del, name='branch_del'),
    url(r'^branchexport/$', branch.branch_export, name='branch_export'),
    url(r'^branchresourceinfo/(?P<branch_id>\d+)/$', branch.resource_detail, name='resource_detail'),
    url(r'^resourceadd/$', resource.resource_add, name='resource_add'),
    url(r'^resource/$', resource.resource_list, name='resource_list'),
    url(r'^resourceedit/(?P<resource_id>\d+)/$', resource.resource_edit, name='resource_edit'),
    url(r'^resourcedel/$', resource.resource_del, name='resource_del'),
    url(r'^resourceexport/$', resource.resource_export, name='resource_export'),
]

cmdb/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from cmdb import api, idc, asset, group, cabinet


urlpatterns = [
    url(r'^asset/$', asset.asset, name='cmdb'),
    url(r'^assetadd/$', asset.asset_add, name='asset_add'),
    url(r'^assetdel/$', asset.asset_del, name='asset_del'),
    url(r'^assetimport/$', asset.asset_import, name='asset_import'),
    url(r'^assetedit/(?P<ids>\d+)/$', asset.asset_edit, name='asset_edit'),
    url(r'^asset/detail/(?P<ids>\d+)/$', asset.server_detail, name='server_detail'),
    # url(r'^asset/save/$', asset.asset_save, name='asset_save'),
    url(r'^group/$', group.group, name='group'),
    url(r'^groupdel/$', group.group_del, name='group_del'),
    url(r'^groupadd/$', group.group_add, name='group_add'),
    url(r'^groupserverlist/(?P<group_id>\d+)/$', group.server_list, name='group_server_list'),
    url(r'^groupedit/(?P<group_id>\d+)/$', group.group_edit, name='group_edit'),
    # url(r'^group/save/$', group.group_save, name='group_save'),
    url(r'^cabinet/$', cabinet.cabinet, name='cabinet'),
    url(r'^cabinetdel/$', cabinet.cabinet_del, name='cabinet_del'),
    url(r'^cabinetadd/$', cabinet.cabinet_add, name='cabinet_add'),
    url(r'^cabinetserverlist/(?P<cabinet_id>\d+)/$', cabinet.server_list, name='cabinet_server_list'),
    url(r'^cabinetedit/(?P<cabinet_id>\d+)/$', cabinet.cabinet_edit, name='cabinet_edit'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idcadd/$', idc.idc_add, name='idc_add'),
    url(r'^idcdel/$', idc.idc_del, name='idc_del'),
    url(r'^idcedit/(?P<idc_id>\d+)/$', idc.idc_edit, name='idc_edit'),
    url(r'^idccabinetlist/(?P<idc_id>\d+)/$', idc.cabinet_list, name='idc_cabinet_list'),
    url(r'^collect', api.collect, name='update_api'),
    url(r'^gethost/', api.get_host, name='get_host'),
    url(r'^getgroup/', api.get_group, name='get_group'),
    url(r'^nodestatus/(?P<ids>\d+)/$', asset.node_status, name='node_status'),
]

mfile/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView
from mfile.views import finder
from django.views.static import serve
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$',finder.as_view(),name='mfile'),
    url(r'^elfinder/',include('elfinder.urls'))
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }),
    ]

branches/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from appconf.models import AppOwner
# Create your models here.


class Region(models.Model):
    name = models.CharField(max_length=255, verbose_name="行政区域", blank=False, unique=True, null=False)
    address = models.CharField(max_length=255, verbose_name="办公地址", blank=True, null=True)
    telephone = models.CharField(max_length=25, verbose_name="联系电话", blank=True, null=True)
    owner = models.ForeignKey(
        AppOwner,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=u"负责人"
    )
    description = models.CharField(max_length=255, verbose_name="备注信息", blank=True, null=True)

    def __unicode__(self):
        return self.name


class Branch(models.Model):
    name = models.CharField(max_length=255, verbose_name="分支机构", blank=False, unique=True, null=False)
    address = models.CharField(max_length=255, verbose_name="办公地址", blank=True, null=True)
    telephone = models.CharField(max_length=25, verbose_name="联系电话", blank=True, null=True)
    owner = models.ForeignKey(
        AppOwner,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=u"负责人"
    )
    region = models.ForeignKey(
        Region,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=u"所属大区"
    )
    description = models.CharField(max_length=255, verbose_name="备注", blank=True, null=True)

    def __unicode__(self):
        return self.name


class Resource(models.Model):
    sn = models.CharField(max_length=255, verbose_name="资源编码", blank=False, null=False)
    name = models.CharField(max_length=255, verbose_name="资源名称", blank=False, null=False)
    spec = models.CharField(max_length=255, verbose_name="资源规格", blank=False, null=False)
    budget = models.CharField(max_length=255, verbose_name="预算金额", blank=True, null=True)
    paid = models.CharField(max_length=255, verbose_name="合同金额", blank=True, null=True)
    contract = models.CharField(max_length=255, verbose_name="合同编号", blank=True, null=True)
    contract_start = models.DateField(max_length=255, verbose_name="合同开始", blank=True, null=True)
    contract_end = models.DateField(verbose_name="合同结束", blank=True, null=True)
    supplier = models.CharField(max_length=255, verbose_name="供应商名", blank=True, null=True)
    service_phone = models.CharField(max_length=25, verbose_name="服务电话", blank=True, null=True)
    branch = models.ForeignKey(
        Branch,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=u"所属机构"
    )
    owner = models.ForeignKey(
        AppOwner,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        verbose_name=u"供应商联系人"
    )
    description = models.CharField(max_length=255, verbose_name="合同说明", blank=True, null=True)

    def __unicode__(self):
        return self.name

branches/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.forms.widgets import *
from branches.models import Branch, Region, Resource
from django.contrib.admin import widgets


class RegionForm(forms.ModelForm):

    class Meta:
        model = Region
        exclude = ("id",)
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'address': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'telephone': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'owner': Select(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'description': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
        }


class BranchForm(forms.ModelForm):

    class Meta:
        model = Branch
        exclude = ("id",)
        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'address': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'telephone': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'owner': Select(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'region': Select(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'description': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),

        }


class ResourceForm(forms.ModelForm):

    class Meta:
        model = Resource
        exclude = ("id",)
        widgets = {
            'sn': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'name': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'spec': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'budget': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'paid': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'contract': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'contract_start': DateInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'contract_end': DateInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'supplier': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'service_phone': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'branch': Select(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'owner': Select(attrs={'class': 'form-control', 'style': 'width:450px;'}),
            'description': Textarea(attrs={'class': 'form-control', 'style': 'width:450px;'}),

        }

branches/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

templates/branches/branch_base.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("branches");
            box.className="active";
            var box2 = document.getElementById("branch");
            box2.className="active";
        }
    </script>

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if branch_id %}
            <form action="{% url 'branch_edit' branch_id %}" method="post">
        {% else %}
            <form action="{% url 'branch_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {% if field.html_name == "owner" %}
                    {{ field.label_tag }} {{ field }}
                    <div class="btn btn-group">
                        <a id="appowneraddmini" style="display: none;" href="#" class="btn btn-success" onclick="return popWin()">添加负责人</a>
                    </div>
                {% else %}
                    {{ field.label_tag }} {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <br>
        <br>
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'branch_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </section>
    {#用于接收appowner_base.html中layui子层的传值#}
    <input id="handle_status" value="" hidden="hidden">
    <input id="new_owner_id" value="" hidden="hidden">
    <input id="new_owner_name" value="" hidden="hidden">
  </div>
<script>
function popWin(){
  layer.open({
      type: 2,
      title: '项目列表',
      area: ['700px', '500px'],
      shadeClose: true, //点击遮罩关闭
      content: ['/appconf/appowneraddmini/'],
      end:function(){
            var handle_status = $("#handle_status").val();
            if ( handle_status == '1' ) {
                layer.msg('添加成功！',{
                    icon: 1,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){
                    var new_owner_id = $("#new_owner_id").val();
                    var new_owner_name = $("#new_owner_name").val();
                    $('#id_owner').append("<option value="+new_owner_id+" selected='selected'>"+new_owner_name+"</option>");
                });
            } else if ( handle_status == '2' ) {
                layer.msg('添加失败！',{
                    icon: 2,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){

                });
            }
      }
  });
}
</script>
{% endblock %}

templates/branches/branch_list.html
{% extends 'base.html' %}
{% load mytags %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/js/base.js"></script>
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.css"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("branches");
            box.className="active";
            var box2 = document.getElementById("branch");
            box2.className="active";
        }
    </script>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->
    <section class="content">
        <form action="" method="post" id="branch_form">
                {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="btn btn-group" style="padding-left: 0">
						 <a id="branchadd" style="display: none;" href="{% url 'branch_add' %}" class="btn btn-success">添加分支</a>
                  </div>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                  <table class="table table-striped table-bordered" id="branchform">
                      <thead>
                        <tr>
                            <th>
                                <input id="checkall" type="checkbox" class="i-checks" name="checkall" value="checkall" data-editable='false' onclick="check_all('branch_form')">
                            </th>
                            <th>分支名称</th>
                            <th>分支地址</th>
                            <th>负责人</th>
                            <th>联系电话</th>
                            <th>操作</th>
                        </tr>
                      </thead>
                            <tbody>
                            {% for branch in all_branch %}
                                <tr class="even gradeX">
                                    <td><input type="checkbox" id="id" class="i-checks" value="{{ branch.id }}" name="id" /></td>
                                    <td><a href="#"><li style="list-style-type:none" onclick="return popWin(this.value)" value="{{ branch.id }}">{{ branch.name }}</li></a> </td>
                                    <td>{{ branch.address }} </td>
                                    <td>{{ branch.owner.name }} </td>
                                    <td>{{ branch.owner.phone }} </td>
                                    <td>
                                        <a id="branchedit" style="display: block; float:left; margin: auto;" href="{% url "branch_edit" branch.id %}"><span class="btn btn-sm btn-info">编辑</span></a>
                                        <a id="branchdel" style="display: block; float:left; margin: auto;" href="{% url "branch_del"%}?id={{ branch.id }}" onclick="return confirm('删除分支？')"><span class="btn btn-sm btn-danger ">删除</span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                  </table>
                  <div class="btn-group">
{#                      <input type="button" id="region_del" class="btn btn-danger"   name="del_button" value="删除区域"/>#}
                  </div>
                </div>
            </div>
        </form>
    </section>

</div>
<script>
  $(function () {
    $('#branchform').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "bAutoWidth": false
    });
  });
</script>

<script>
    $('#region_del').click(function () {
        var region_id_all = getIDall();
        if (region_id_all == ''){
            alert("请至少选择一行!");
            return false;
        }
        if (confirm("确定删除?")) {
            $.ajax({
                type: "post",
                data: {region_id_all: region_id_all,csrfmiddlewaretoken: '{{ csrf_token }}'},
                url: "{% url 'region_del' %}",
                success: function () {
                    parent.location.reload();
                }
            });
        }
    });
</script>

<script>
function popWin(region_id){
  layer.open({
      type: 2,
      title: '项目列表',
      area: ['700px', '500px'],
      shadeClose: true, //点击遮罩关闭
      content: ['/branches/branchresourceinfo/' + region_id]
  });
}
</script>
{% endblock %}

templates/branches/branch_resource_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'link_css.html' %}
    {% include 'head_script.html' %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/js/base.js"></script>
    <script src="/static/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="/static/plugins/datatables/dataTables.bootstrap.css"></script>
</head>
<body>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    <section class="content">
        <div class="box">
                <div class="box-body">
                  <table class="table table-striped table-bordered" id="product_project_table">
                      <thead>
                        <tr>
                            <th>资源名称</th>
                            <th>资源规格</th>
                            <th>预算金额</th>
                            <th>实际金额</th>
                            <th>合同编号</th>
                            <th>合同开始</th>
                            <th>合同结束</th>
                            <th>供应商名</th>
                        </tr>
                      </thead>
                            <tbody>
                            {% for r in resources %}
                                <tr class="even gradeX">
                                    <td><a href="{% url "resource_edit" r.id %}" target="_blank">{{ r.name }}</a></td>
                                    <td>{{ r.spec }} </td>
                                    <td>{{ r.budget }} </td>
                                    <td>{{ r.paid }} </td>
                                    <td>{{ r.contract }} </td>
                                    <td>{{ r.contract_start }} </td>
                                    <td>{{ r.contract_end }} </td>
                                    <td>{{ r.supplier }} </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                  </table>
                </div>
        </div>
    </section>
</div>
<script>
  $(function () {
    $('#product_project_table').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": true
    });
  });
</script>
</body>
</html>

templates/branches/header.html
<header class="main-header">

    <!-- Logo -->
    <a href="{% url 'index' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>AST</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>AdminSet</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li style="font-size: medium" id="region"><a href="{% url 'region_list' %}"><b>行政区域</b></a></li>
            <li style="font-size: medium" id="branch"><a href="{% url 'branch_list' %}"><b>分支机构</b></a></li>
            <li style="font-size: medium" id="resource"><a href="{% url 'resource_list' %}"><b>资源管理</b></a></li>
          </ul>
        </div>
      <!-- Navbar Right Menu -->
      {% include 'navbar-custom-menu.html' %}
    </nav>
  </header>

templates/branches/region_base.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("branches");
            box.className="active";
            var box2 = document.getElementById("region");
            box2.className="active";
        }
    </script>

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if region_id %}
            <form action="{% url 'region_edit' region_id %}" method="post">
        {% else %}
            <form action="{% url 'region_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {% if field.html_name == "owner" %}
                    {{ field.label_tag }} {{ field }}
                    <div class="btn btn-group"></div>
                    <a id="appowneraddmini" style="display: none;" href="#" onclick="return popWin()"><li class="btn btn-success" ><b>添加负责人</b></li></a>
                {% else %}
                    {{ field.label_tag }} {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <br>
        <br>
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'region_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </section>
    {#用于接收appowner_base.html中layui子层的传值#}
    <input id="handle_status" value="" hidden="hidden">
    <input id="new_owner_id" value="" hidden="hidden">
    <input id="new_owner_name" value="" hidden="hidden">
  </div>
<script>
function popWin(){
  layer.open({
      type: 2,
      title: '项目列表',
      area: ['700px', '500px'],
      shadeClose: true, //点击遮罩关闭
      content: ['/appconf/appowneraddmini/'],
      end:function(){
            var handle_status = $("#handle_status").val();
            if ( handle_status == '1' ) {
                layer.msg('添加成功！',{
                    icon: 1,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){
                    var new_owner_id = $("#new_owner_id").val();
                    var new_owner_name = $("#new_owner_name").val();
                    $('#id_owner').append("<option value="+new_owner_id+" selected='selected'>"+new_owner_name+"</option>");
                });
            } else if ( handle_status == '2' ) {
                layer.msg('添加失败！',{
                    icon: 2,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){

                });
            }
      }
  });
}
</script>
{% endblock %}

templates/branches/resource_base.html
{% extends 'base.html' %}
{% block self_head_css_js %}
    <script src="/static/layer/layer.js"></script>
    <script src="/static/plugins/jquery-ui-1.12/jquery-ui.js"></script>
    <link rel="stylesheet" href="/static/plugins/jquery-ui-1.12/jquery-ui.css">

{% endblock %}
{% block content %}

    <script>
        window.onload=init;
        function init() {
            var box = document.getElementById("branches");
            box.className="active";
            var box2 = document.getElementById("resource");
            box2.className="active";
        }
      $(function() {
    $( "#id_contract_start" ).datepicker({language: 'CN'});
    $( "#id_contract_end" ).datepicker();
    });
    </script>

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>

    <!-- Main content -->

    <section class="content">

      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
        </div>
        <div class="box-body">
        {% if resource_id %}
            <form action="{% url 'resource_edit' resource_id %}" method="post">
        {% else %}
            <form action="{% url 'resource_add' %}" method="post">
        {% endif %}
        {% csrf_token %}
{#        {{ form.as_p }}#}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {% if field.html_name == "owner" %}
                    {{ field.label_tag }} {{ field }}
                    <div class="btn btn-group">
                        <a href="#" onclick="return popWin()"><li class="btn btn-success" ><b>添加负责人</b></li></a>
                    </div>
                {% else %}
                    {{ field.label_tag }} {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <br>
        <br>
        <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'resource_list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
          </form>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <i class="fa fa-info-circle"></i> 请勿重复添加条目
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->
    </section>
    {#用于接收appowner_base.html中layui子层的传值#}
    <input id="handle_status" value="" hidden="hidden">
    <input id="new_owner_id" value="" hidden="hidden">
    <input id="new_owner_name" value="" hidden="hidden">
  </div>
<script>
function popWin(){
  layer.open({
      type: 2,
      title: '项目列表',
      area: ['700px', '500px'],
      shadeClose: true, //点击遮罩关闭
      content: ['/appconf/appowneraddmini/'],
      end:function(){
            var handle_status = $("#handle_status").val();
            if ( handle_status == '1' ) {
                layer.msg('添加成功！',{
                    icon: 1,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){
                    var new_owner_id = $("#new_owner_id").val();
                    var new_owner_name = $("#new_owner_name").val();
                    $('#id_owner').append("<option value="+new_owner_id+" selected='selected'>"+new_owner_name+"</option>");
                });
            } else if ( handle_status == '2' ) {
                layer.msg('添加失败！',{
                    icon: 2,
                    time: 2000 //2秒关闭（如果不配置，默认是3秒）
                },function(){

                });
            }
      }
  });
}
</script>
{% endblock %}